# Loop feature will be removed in version
- hosts: andrew
  become: true
  tasks:
   - name: Install list of packages
     yum:
       name: ['nano', 'wget', 'vim', 'zip', 'unzip']
     when: ("ansible_distribution" == "RedHat")
